package etiquetas;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cgsen
 */
public class InicialEnglish extends javax.swing.JFrame {

    String user = System.getProperty("user.name");
    String ruta = ("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\Etiquetas\\fotoCursos\\");
    String rutaFoto = ("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\Etiquetas\\");
    String empresaFile = ("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\Etiquetas\\fotoCam");
    String trabajadorFile = ("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\Etiquetas\\fotoCam\\");

    /**
     * Creates new form InicialEnglish
     */
    public InicialEnglish() {
        initComponents();
        this.setTitle("Inicio");
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/IconoJFrame.png")).getImage());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);

        File carpeta = new File(empresaFile);
        String[] listado = carpeta.list();

        if (listado == null || listado.length == 0) {
            JOptionPane.showMessageDialog(null, "\nNo folder exists.");
            return;
        } else {
            for (String listado1 : listado) {
                jComboEmpresa.addItem(listado1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jCheckBoxplataformaelevadora = new javax.swing.JCheckBox();
        jCheckBoxmedioselevacion = new javax.swing.JCheckBox();
        jCheckBoxmontajeandamios = new javax.swing.JCheckBox();
        jCheckBoxCarretillaelevadora = new javax.swing.JCheckBox();
        jCheckBoxrecursopreventivo = new javax.swing.JCheckBox();
        jCheckBoxprlbasico = new javax.swing.JCheckBox();
        jCheckBoxespaciosconfinados = new javax.swing.JCheckBox();
        jCheckBoxAtmosferasExplosivas = new javax.swing.JCheckBox();
        jCheckBoxHazardousEnergy = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnInsertarFoto = new javax.swing.JButton();
        jlabelNomEmpresa = new javax.swing.JLabel();
        jlabelNomTrabajador = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jCheckBoxTrabajoaltura = new javax.swing.JCheckBox();
        txtFecha = new javax.swing.JTextField();
        jlabelNomTrabajador1 = new javax.swing.JLabel();
        jComboEmpresa = new javax.swing.JComboBox<>();
        jComboEmpleado = new javax.swing.JComboBox<>();
        btnFotos = new javax.swing.JButton();
        impresion1 = new etiquetas.Impresion();
        jLabelCarretillaelevadora = new javax.swing.JLabel();
        jLabelAtmosoferasExplosivas = new javax.swing.JLabel();
        jLabelmontajeandamios = new javax.swing.JLabel();
        jLabelplataformaelevadora = new javax.swing.JLabel();
        jLabelrecursopreventivo = new javax.swing.JLabel();
        jlabelFoto = new javax.swing.JLabel();
        txtNomEmprFoto = new javax.swing.JTextField();
        jLabelTrabajoaltura = new javax.swing.JLabel();
        jLabelprlbasico = new javax.swing.JLabel();
        jLabelmedioselevación = new javax.swing.JLabel();
        jlabelHazardousEnergy = new javax.swing.JLabel();
        jLabelEspaciosConfinados = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuPrincipal = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(104, 144, 196));

        jCheckBoxplataformaelevadora.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxplataformaelevadora.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxplataformaelevadora.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxplataformaelevadora.setText("Lifting Platfrom Training");
        jCheckBoxplataformaelevadora.setBorder(null);
        jCheckBoxplataformaelevadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxplataformaelevadoraActionPerformed(evt);
            }
        });

        jCheckBoxmedioselevacion.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxmedioselevacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxmedioselevacion.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxmedioselevacion.setText("Hoisted Loads Training");
        jCheckBoxmedioselevacion.setBorder(null);
        jCheckBoxmedioselevacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxmedioselevacionActionPerformed(evt);
            }
        });

        jCheckBoxmontajeandamios.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxmontajeandamios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxmontajeandamios.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxmontajeandamios.setText("Scaffolding Assembly Training");
        jCheckBoxmontajeandamios.setBorder(null);
        jCheckBoxmontajeandamios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxmontajeandamiosActionPerformed(evt);
            }
        });

        jCheckBoxCarretillaelevadora.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxCarretillaelevadora.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxCarretillaelevadora.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxCarretillaelevadora.setText("Forklifts Training");
        jCheckBoxCarretillaelevadora.setBorder(null);
        jCheckBoxCarretillaelevadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCarretillaelevadoraActionPerformed(evt);
            }
        });

        jCheckBoxrecursopreventivo.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxrecursopreventivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxrecursopreventivo.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxrecursopreventivo.setText("Appointment Preventive Resource");
        jCheckBoxrecursopreventivo.setBorder(null);
        jCheckBoxrecursopreventivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxrecursopreventivoActionPerformed(evt);
            }
        });

        jCheckBoxprlbasico.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxprlbasico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxprlbasico.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxprlbasico.setText("Safety Officer PRL Training 50H");
        jCheckBoxprlbasico.setBorder(null);
        jCheckBoxprlbasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxprlbasicoActionPerformed(evt);
            }
        });

        jCheckBoxespaciosconfinados.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxespaciosconfinados.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxespaciosconfinados.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxespaciosconfinados.setText("Confined Space Training");
        jCheckBoxespaciosconfinados.setBorder(null);
        jCheckBoxespaciosconfinados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxespaciosconfinadosActionPerformed(evt);
            }
        });

        jCheckBoxAtmosferasExplosivas.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxAtmosferasExplosivas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxAtmosferasExplosivas.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxAtmosferasExplosivas.setText("Explosive Atmospheres Training");
        jCheckBoxAtmosferasExplosivas.setBorder(null);
        jCheckBoxAtmosferasExplosivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAtmosferasExplosivasActionPerformed(evt);
            }
        });

        jCheckBoxHazardousEnergy.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHazardousEnergy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxHazardousEnergy.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxHazardousEnergy.setText("Electric Hards Training");
        jCheckBoxHazardousEnergy.setBorder(null);
        jCheckBoxHazardousEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHazardousEnergyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bunge Western Europe");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(0, 0, 255));
        btnPrint.setText("Print");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnInsertarFoto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInsertarFoto.setForeground(new java.awt.Color(0, 0, 255));
        btnInsertarFoto.setText("Insert photo");
        btnInsertarFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFotoActionPerformed(evt);
            }
        });

        jlabelNomEmpresa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabelNomEmpresa.setForeground(new java.awt.Color(0, 0, 255));
        jlabelNomEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelNomEmpresa.setText("Company name");

        jlabelNomTrabajador.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabelNomTrabajador.setForeground(new java.awt.Color(0, 0, 255));
        jlabelNomTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelNomTrabajador.setText("Employee Name");

        btnLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiar.setText("Clean up");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jCheckBoxTrabajoaltura.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTrabajoaltura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxTrabajoaltura.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxTrabajoaltura.setText("Work at Height Training");
        jCheckBoxTrabajoaltura.setBorder(null);
        jCheckBoxTrabajoaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTrabajoalturaActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setToolTipText("<html>Write the date.<br/></html>");
        txtFecha.setBorder(null);

        jlabelNomTrabajador1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabelNomTrabajador1.setForeground(new java.awt.Color(0, 0, 255));
        jlabelNomTrabajador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelNomTrabajador1.setText("Date");

        jComboEmpresa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboEmpresa.setForeground(new java.awt.Color(0, 0, 255));
        jComboEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEmpresaActionPerformed(evt);
            }
        });

        jComboEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboEmpleado.setForeground(new java.awt.Color(0, 0, 255));

        btnFotos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFotos.setForeground(new java.awt.Color(0, 0, 255));
        btnFotos.setText("Photos");
        btnFotos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotosActionPerformed(evt);
            }
        });

        jLabelCarretillaelevadora.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAtmosoferasExplosivas.setBackground(new java.awt.Color(255, 255, 255));

        jLabelmontajeandamios.setBackground(new java.awt.Color(255, 255, 255));

        jLabelplataformaelevadora.setBackground(new java.awt.Color(255, 255, 255));

        jLabelrecursopreventivo.setBackground(new java.awt.Color(255, 255, 255));

        jlabelFoto.setBackground(new java.awt.Color(255, 255, 255));
        jlabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtNomEmprFoto.setEditable(false);
        txtNomEmprFoto.setBackground(new java.awt.Color(255, 255, 255));
        txtNomEmprFoto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtNomEmprFoto.setForeground(new java.awt.Color(0, 0, 255));
        txtNomEmprFoto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomEmprFoto.setText("Company - Worker - Date");
        txtNomEmprFoto.setAutoscrolls(false);
        txtNomEmprFoto.setBorder(null);

        jLabelTrabajoaltura.setBackground(new java.awt.Color(255, 255, 255));

        jLabelprlbasico.setBackground(new java.awt.Color(255, 255, 255));

        jLabelmedioselevación.setBackground(new java.awt.Color(255, 255, 255));

        jlabelHazardousEnergy.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEspaciosConfinados.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout impresion1Layout = new javax.swing.GroupLayout(impresion1);
        impresion1.setLayout(impresion1Layout);
        impresion1Layout.setHorizontalGroup(
            impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, impresion1Layout.createSequentialGroup()
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEspaciosConfinados, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarretillaelevadora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabelHazardousEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAtmosoferasExplosivas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelmedioselevación, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelmontajeandamios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelprlbasico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelplataformaelevadora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTrabajoaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelrecursopreventivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtNomEmprFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        impresion1Layout.setVerticalGroup(
            impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(impresion1Layout.createSequentialGroup()
                .addGroup(impresion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addComponent(jLabelCarretillaelevadora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEspaciosConfinados, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addComponent(jLabelAtmosoferasExplosivas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelHazardousEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addComponent(jLabelmontajeandamios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelmedioselevación, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addComponent(jLabelplataformaelevadora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelprlbasico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addComponent(jLabelrecursopreventivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTrabajoaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(impresion1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNomEmprFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxAtmosferasExplosivas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxHazardousEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxCarretillaelevadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxespaciosconfinados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxmedioselevacion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxrecursopreventivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxprlbasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxplataformaelevadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxmontajeandamios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxTrabajoaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(impresion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInsertarFoto)))))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFondoLayout.createSequentialGroup()
                                        .addGap(324, 324, 324)
                                        .addComponent(jlabelNomTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlabelNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jComboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelNomTrabajador1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelNomTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabelNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabelNomTrabajador1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jCheckBoxHazardousEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxAtmosferasExplosivas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCarretillaelevadora))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addComponent(jCheckBoxmontajeandamios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxplataformaelevadora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxprlbasico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxespaciosconfinados)
                    .addComponent(jCheckBoxrecursopreventivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxmedioselevacion)
                    .addComponent(jCheckBoxTrabajoaltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(impresion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(btnFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMenuPrincipal.setBorder(null);
        btnMenuPrincipal.setForeground(new java.awt.Color(0, 0, 255));
        btnMenuPrincipal.setMnemonic('m');
        btnMenuPrincipal.setText("Menu");
        btnMenuPrincipal.setToolTipText("<html>Main menu<br/>You can also use Alt + m<br/><html/>");
        btnMenuPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setMnemonic('s');
        btnSalir.setText("Leave");
        btnSalir.setToolTipText("<html>Click to exit.<br/>You can also use Alt + s<br/></html>");
        btnSalir.setBorder(null);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnMenuPrincipal.add(btnSalir);

        jMenuBar1.add(btnMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertarFoto() {
        try {
            if (jComboEmpresa.getSelectedItem().toString().equals("") || jComboEmpleado.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "\nYou will have to fill in the details.");
            } else {
                File carpeta = new File(rutaFoto + "fotoCam\\" + jComboEmpresa.getSelectedItem().toString());
                File prueba = new File(carpeta + "\\" + jComboEmpleado.getSelectedItem().toString());
                if (!carpeta.exists()) {
                    JOptionPane.showMessageDialog(null, "\nThe company does not exist.");
                } else if (!prueba.exists()) {
                    JOptionPane.showMessageDialog(null, "\nthe person does not exist.");
                } else if (prueba.exists()) {
                    BufferedImage bufferedImage = ImageIO.read(new File(carpeta + "\\" + jComboEmpleado.getSelectedItem().toString()));
                    Image image = bufferedImage.getScaledInstance(119, 128, Image.SCALE_DEFAULT);
                    ImageIcon icon = new ImageIcon(image);
                    jlabelFoto.setIcon(icon);
                    int confirmado = JOptionPane.showOptionDialog(null,
                            "Do you want to create the data in the label?",
                            "Label data",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null, new Object[]{"Yes", "No"}, "Yes");
                    switch (confirmado) {
                        case JOptionPane.OK_OPTION:
                            String entradaUsuario = JOptionPane.showInputDialog("Write the label details");
                            txtNomEmprFoto.setText(entradaUsuario);
                            break;
                        case JOptionPane.NO_OPTION:
                            if (txtFecha.getText().equals("")) {
                                Date fecha_actual = new Date();
                                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                                String nombre = jComboEmpleado.getSelectedItem().toString();
                                String nombreEtiqueta = nombre.substring(0, nombre.lastIndexOf("."));
                                JOptionPane.showMessageDialog(null, "These are the tag details:\n"
                                        + jComboEmpresa.getSelectedItem().toString() + " - " + nombreEtiqueta + " - " + formatoFecha.format(fecha_actual));
                                txtNomEmprFoto.setText(jComboEmpresa.getSelectedItem().toString() + " - " + nombreEtiqueta + " - " + formatoFecha.format(fecha_actual));
                            } else {
                                String nombre = jComboEmpleado.getSelectedItem().toString();
                                String nombreEtiqueta = nombre.substring(0, nombre.lastIndexOf("."));
                                JOptionPane.showMessageDialog(null, "The names of the 'Company - Worker - Date' will be written.");
                                txtNomEmprFoto.setText(jComboEmpresa.getSelectedItem().toString() + " - " + nombreEtiqueta + " - " + txtFecha.getText());
                            }
                    }
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "\nError inserting data.");
        }
    }

    public void limpiar() {
        jLabelTrabajoaltura.setIcon(null);
        jLabelrecursopreventivo.setIcon(null);
        jLabelprlbasico.setIcon(null);
        jLabelplataformaelevadora.setIcon(null);
        jLabelmontajeandamios.setIcon(null);
        jLabelmedioselevación.setIcon(null);
        jlabelHazardousEnergy.setIcon(null);
        jLabelAtmosoferasExplosivas.setIcon(null);
        jLabelCarretillaelevadora.setIcon(null);
        jLabelEspaciosConfinados.setIcon(null);
        jlabelFoto.setIcon(null);
        txtNomEmprFoto.setText("Company - Worker - Date");
        jComboEmpleado.removeAllItems();
        txtFecha.setText(null);
    }

    public void abrirFotos() {
        try {
            Process p = new ProcessBuilder("explorer.exe", "/," + trabajadorFile).start();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error showing the files");
        }
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jCheckBoxplataformaelevadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxplataformaelevadoraActionPerformed
        if (jCheckBoxplataformaelevadora.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "plataforma elevadora.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelplataformaelevadora.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelplataformaelevadora.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxplataformaelevadoraActionPerformed

    private void jCheckBoxmedioselevacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxmedioselevacionActionPerformed
        if (jCheckBoxmedioselevacion.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "medios de elevación.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelmedioselevación.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelmedioselevación.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxmedioselevacionActionPerformed

    private void jCheckBoxmontajeandamiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxmontajeandamiosActionPerformed
        if (jCheckBoxmontajeandamios.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "montaje andamios.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelmontajeandamios.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelmontajeandamios.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxmontajeandamiosActionPerformed

    private void jCheckBoxCarretillaelevadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCarretillaelevadoraActionPerformed
        if (jCheckBoxCarretillaelevadora.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "Carretilla elevadora.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelCarretillaelevadora.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelCarretillaelevadora.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxCarretillaelevadoraActionPerformed

    private void jCheckBoxrecursopreventivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxrecursopreventivoActionPerformed
        if (jCheckBoxrecursopreventivo.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "recurso preventivo.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelrecursopreventivo.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelrecursopreventivo.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxrecursopreventivoActionPerformed

    private void jCheckBoxprlbasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxprlbasicoActionPerformed
        if (jCheckBoxprlbasico.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "prl básico.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelprlbasico.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelprlbasico.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxprlbasicoActionPerformed

    private void jCheckBoxespaciosconfinadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxespaciosconfinadosActionPerformed
        if (jCheckBoxespaciosconfinados.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "espacios confinados.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelEspaciosConfinados.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelEspaciosConfinados.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxespaciosconfinadosActionPerformed

    private void jCheckBoxAtmosferasExplosivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAtmosferasExplosivasActionPerformed
        if (jCheckBoxAtmosferasExplosivas.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "atmosferas explosivas.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelAtmosoferasExplosivas.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelAtmosoferasExplosivas.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxAtmosferasExplosivasActionPerformed

    private void jCheckBoxHazardousEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHazardousEnergyActionPerformed
        if (jCheckBoxHazardousEnergy.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "Hazardous Energy.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jlabelHazardousEnergy.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jlabelHazardousEnergy.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxHazardousEnergyActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(impresion1);
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Something has failed");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnInsertarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFotoActionPerformed
        insertarFoto();
    }//GEN-LAST:event_btnInsertarFotoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jCheckBoxTrabajoalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTrabajoalturaActionPerformed
        if (jCheckBoxTrabajoaltura.isSelected()) {
            BufferedImage bufferedImage;
            try {
                bufferedImage = ImageIO.read(new File(ruta + "Trabajo en altura.png"));
                Image image = bufferedImage.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                jLabelTrabajoaltura.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelTrabajoaltura.setIcon(null);
        }
    }//GEN-LAST:event_jCheckBoxTrabajoalturaActionPerformed

    private void jComboEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEmpresaActionPerformed
        jComboEmpleado.removeAllItems();
        String selectjComboEmpresa = jComboEmpresa.getSelectedItem().toString();
        File carpeta2 = new File(trabajadorFile + selectjComboEmpresa);
        String[] listado2 = carpeta2.list();
        if (listado2 == null || listado2.length == 0) {
            JOptionPane.showMessageDialog(null, "\nThis company does not have any employee photos.");
        } else {
            for (String listado3 : listado2) {
                jComboEmpleado.addItem(listado3);
            }
        }
    }//GEN-LAST:event_jComboEmpresaActionPerformed

    private void btnFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotosActionPerformed
        abrirFotos();
    }//GEN-LAST:event_btnFotosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFotos;
    private javax.swing.JButton btnInsertarFoto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JMenu btnMenuPrincipal;
    private javax.swing.JButton btnPrint;
    private javax.swing.JMenuItem btnSalir;
    private etiquetas.Impresion impresion1;
    private javax.swing.JCheckBox jCheckBoxAtmosferasExplosivas;
    private javax.swing.JCheckBox jCheckBoxCarretillaelevadora;
    private javax.swing.JCheckBox jCheckBoxHazardousEnergy;
    private javax.swing.JCheckBox jCheckBoxTrabajoaltura;
    private javax.swing.JCheckBox jCheckBoxespaciosconfinados;
    private javax.swing.JCheckBox jCheckBoxmedioselevacion;
    private javax.swing.JCheckBox jCheckBoxmontajeandamios;
    private javax.swing.JCheckBox jCheckBoxplataformaelevadora;
    private javax.swing.JCheckBox jCheckBoxprlbasico;
    private javax.swing.JCheckBox jCheckBoxrecursopreventivo;
    private javax.swing.JComboBox<String> jComboEmpleado;
    private javax.swing.JComboBox<String> jComboEmpresa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAtmosoferasExplosivas;
    private javax.swing.JLabel jLabelCarretillaelevadora;
    private javax.swing.JLabel jLabelEspaciosConfinados;
    private javax.swing.JLabel jLabelTrabajoaltura;
    private javax.swing.JLabel jLabelmedioselevación;
    private javax.swing.JLabel jLabelmontajeandamios;
    private javax.swing.JLabel jLabelplataformaelevadora;
    private javax.swing.JLabel jLabelprlbasico;
    private javax.swing.JLabel jLabelrecursopreventivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlabelFoto;
    private javax.swing.JLabel jlabelHazardousEnergy;
    private javax.swing.JLabel jlabelNomEmpresa;
    private javax.swing.JLabel jlabelNomTrabajador;
    private javax.swing.JLabel jlabelNomTrabajador1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNomEmprFoto;
    // End of variables declaration//GEN-END:variables
}
